### ISSUE TITLE
[Android]A native text is not displayed after resuming of the application.

### ISSUE THREAD

**Issue by utibenkei** [bazzisoft-openfl-extensions/nativetext#2]
Since the problem occurred in the android device, it reports. 
The application was resumed, after pushing the "back" button and paused an application. 
Then, a native text is no longer displayed. 
Is there any method of avoiding this problem?

**Comment by bazzisoft** [comment]
Good catch. I can't explain why this is happening, but commit https://github.com/bazzisoft-openfl-extensions/nativetext/commit/d8b8488460428bcf98fd2258d25460443239abd1 seems to fix it on mine.

**Comment by utibenkei** [comment]
seems ok, thanks very much!
