### ISSUE TITLE
Missing return Dynamic 

### ISSUE THREAD

**Issue by PXshadow** [bazzisoft-openfl-extensions/nativetext#5]
lines 112-123 Missing return Dynamic NativeTextField.hx 

    private function PrepareConfigForNativeCall(config:NativeTextFieldConfig) : Dynamic
    {
        #if android
        var jsonConfig = (null == config ? null : Json.stringify(config));	
        return jsonConfig;
        #elseif cpp
        var intConfig:Dynamic = Reflect.copy(config);
        intConfig.textAlignment = EnumToInt(config.textAlignment);
        intConfig.keyboardType = EnumToInt(config.keyboardType);
        intConfig.returnKeyType = EnumToInt(config.returnKeyType);        
        return intConfig;
        #end
    }

I put the nativeText folder and extension kit in my project folder. included path to nativetext. And used the example code of nativetext  in the first create function. Any help is super apperciated! 😄

**Comment by bazzisoft** [comment]
@PXshadow I haven't used this for a couple of years now so pretty rusty. From the error message it seems there is not "return", so whatever platform you're compiling for is not being detected by the #if or @#elseif directives. Please check what the correct platform labels are for the #if directive for your target platform & adjust the code accordingly.

**Comment by PXshadow** [comment]
Alright thank you I really appreciate it, working great now!

**Comment by bazzisoft** [comment]
Great!
